### ISSUE TITLE
License File - Copyright holder change

### ISSUE THREAD

**Issue by ZNixian** [X52p/KerbinReality#2]
Hi, just noticed you changed the name of the copyright holder in your LICENSE file. While I doubt @Vivero minds, I thought it would be a good idea to let you know that this does violate the MIT license, which is probably useful to know if you're working on other projects in the future.

I think this is (from memory this was on the GNU website which has a wealth of well-written information about software licenses and copyright in general, though it may have been from another large and reputable FOSS group) the correct way to make such a change:

```
Copyright (c) 2016 Vivero
Copyright (c) 2018 X52p
```

**Comment by X52p** [comment]
I didn't know that. I have changed it, thanks for the advice!

**Comment by ZNixian** [comment]
No problem.
