### ISSUE TITLE
Missing assemblies and methods

### ISSUE THREAD

**Issue by ZNixian** [X52p/KerbinReality#3]
Hi, a couple of problems I noticed when trying to compile:

- `UnityEngine.VR.dll` does not exist in either the `KSP_Data` or `KSP_x64_Data` directories.
- `GameObject.AddOrGetComponent` does not appear to be defined, however I suspect it's caused by the above issues.

**Comment by X52p** [comment]
I experimented with `UnityEngine.VR.dll` but it should not be used anymore. It can be removed.
`GameObject.AddOrGetComponent` is part of the KSP API:
https://kerbalspaceprogram.com/api/class_game_object_extension.html#a6dd665493f29659a290367986802ea54
But it should be posible to replace it with `GameObject.addComponent `in the cases where I used it.

edit:
I removed UnityEngine.VR.dll from the dependencies. Please tell me if the problem persists.
