### ISSUE TITLE
History Rebase

### ISSUE THREAD

**Issue by ZNixian** [X52p/KerbinReality#4]
Hi,

I've rebased a copy of this repo, such that it uses KerbalVR's history, and also did some work on cleaning up the history such that unrelated changes are moved into their own commits.

This should make using `git blame` and similar commands reasonable to use.

With some very minor exceptions, the files you'd get from checking it out are identical to those in this repo, with the following exceptions:

- deleted:   KerbalVR.VC.db - This is the Visual Studio Intellisense database, and is automatically generated when the project is opened.
- modified:   .gitignore - Ignore *.VC.db, see above
- deleted:   KerbalVR/lib/win32/openvr_api.dll - With the new DLL as `KerbalVR/openvr_api.dll`, I don't believe this file is referenced from anywhere.
- deleted:   KerbalVR/lib/win64/openvr_api.dll - Same as above
- deleted:   KerbalVR/openvr.h - while I couldn't get even the vanilla version of this mod working (see #3), I can't see why this would be used anywhere as it's a C++ header file.
- modified:   LICENSE - applies fix from #2

https://github.com/ZNixian/KerbinReality/tree/rebased

I've opened this as an issue rather than a pull request is because I'm not sure how well a git merge will cope with replacing the entire commit history - it would be much better to clone it and `git push --force` it.

**Comment by X52p** [comment]
Do you mean I should clone ZNixian/KerbinReality/tree/rebased repository and force push it into X52p/KerbinReality?

**Comment by ZNixian** [comment]
First make a new branch with the current history on, in case it's needed in the future for whatever reason.

After that, yes.

In case you're not aware of it, `ZNixian/KerbinReality/tree/rebased` isn't a repo - it's address of the GitHub UI to view the `rebased` branch.

To do this, here's the commands you need:

```
git remote add znix `https://github.com/ZNixian/KerbinReality.git`
git fetch znix
git reset --soft znix/rebased
```

This adds and fetches my fork, loads in the `rebased` branch from my fork onto HEAD (although it shouldn't change the files in your working copy).

If there are any differences between your working copy and the rebased copy, you can view them with `git diff HEAD`, stage bits of changes with `git add --patch`, and remove local changes with `git checkout --patch`

When you're ready, force push it:

```
git push --force
```

(sorry if you already knew all the above, I wasn't sure if you did or not)

**Comment by X52p** [comment]
Thanks for the step by step manual. I don't have a lot of experience with git. I hope I've done everything correctly.

**Comment by ZNixian** [comment]
Everything looks great, you're welcome.
